handler_test.go: allow extra headers
The current gRPC seems to add a "content-type" header automatically,
causing the tests to fail with:

    --- FAIL: TestProxyHappySuite/TestPingCarriesServerHeadersAndTrailers (0.00s)
    	handler_test.go:138:
    			Error Trace:	handler_test.go:138
    			Error:      	"map[test-client-header:[I like turtles.] content-type:[application/grpc]]" should have 1 item(s), but has 2
    			Test:       	TestProxyHappySuite/TestPingCarriesServerHeadersAndTrailers
    			Messages:   	server response headers must contain server data
    --- FAIL: TestProxyHappySuite/TestPingStream_FullDuplexWorks (0.01s)
    	handler_test.go:173:
    			Error Trace:	handler_test.go:173
    			Error:      	"map[content-type:[application/grpc] test-client-header:[I like turtles.]]" should have 1 item(s), but has 2
    			Test:       	TestProxyHappySuite/TestPingStream_FullDuplexWorks
    			Messages:   	PingStream response headers user contain metadata

Instead of checking the length and assuming that the header is the
right one, now these two lines check for the existence of the
"test-client-header" header.